### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by rafraser**

### CODE REVIEW

**Comment by Kesefon** [comment]
I think the 3 separate UpdateDiscordStatus functions are kinda ugly and they're still missing the endTimestamp field (maybe more). 
My idea was to replace them with a single function that takes a table as input. This should make it possible to set all fields that discord accepts from Lua without making them required. 
I can look into implementing this, if you think it's a good idea. 
The Lua side would look like this: 
rpcData = {}
rpcData["state"] = "ingame"
updateRPC(rpcData)

**Comment by rafraser** [comment]
Yeah, that's what I was planning on doing but I couldn't find great documentation on how to go about that. Feel free to open a PR with any changes you think are good.

I've been experimenting a fair bit with the joining/spectating stuff and as far as I can tell they're useless for what we're doing, so if you'd rather get rid of that stuff feel free

**Comment by Kesefon** [comment]
I use the [LuaBase header](https://github.com/Facepunch/gmod-module-base/blob/development/include/GarrysMod/Lua/LuaBase.h) as documentation and guess the rest.

I don't have a good use for the joining/spectating stuff either, but it might be useful, when integrated in a gamemode. I would just leave it as is unless it causes problems.

**Comment by rafraser** [comment]
It's pretty much impossible to get working unless people are already connected to a server... which would defeat the purpose of the join game button anyway. Easy enough to keep it at least.

**Pull request closed without merging**
